---
# Source: F5Demo/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: fatstacks-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "f5demo",
        "label": "Big Money App",
        "remark": "Example of using CIS ConfigMap",
        "BigMoney": {
          "class": "Tenant",
          "CaChing": {
             "class": "Application",
             "template": "generic",
             "frontend": {
                "class": "Service_TCP",
                "virtualAddresses": ["10.1.10.101"],
               "remark":"frontend: fatstacks.tcp.v1",
               "persistenceMethods":[],
               "virtualPort": 8888,
                "pool": "fatstack_pool",
                "shareAddresses": true
             },
             "fatstack_pool": {
                "class": "Pool",
                "monitors": [ "tcp" ],
                "members": [{
                   "servicePort": 8080,
                   "serverAddresses": [],
                   "shareNodes": true
                }]
             }
       }
       }
    }
    }
    

